events {
  worker_connections 1024;
}

http {
  upstream django_upstream {
    server django:8000;
  }

  # Load Balancer برای سرویس محصول:
  # درخواست‌ها نوبتی بین golang1 و golang2 پخش می‌شوند
  upstream golang_upstream {
    server golang1:8080;
    server golang2:8080;
  }

  server {
    listen 80;
    server_name _;

    location /api/auth/ {
      proxy_pass http://django_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Authorization $http_authorization;
    }

    location /api/stores/ {
      proxy_pass http://django_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Authorization $http_authorization;
    }

    location /admin/ {
      proxy_pass http://django_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/products/ {
      proxy_pass http://golang_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Authorization $http_authorization;
    }

    location /health {
      proxy_pass http://golang_upstream/health;
      proxy_set_header Host $host;
    }

    location /healthz {
      return 200 "OK";
      add_header Content-Type text/plain;
    }
  }
}
