FROM golang:1.23-alpine AS build

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /product-service .

FROM alpine:3.20
WORKDIR /app
COPY --from=build /product-service /app/product-service
EXPOSE 8080
CMD ["/app/product-service"]
